#!/bin/bash

TOTP_SECRET='YOUR_2FA_TOTP_SECRET'
PASSWORD_SHA256='YOUR_2FA_PASSWORD_SHA256'

TOTP_AUTH_TOKEN="$(/usr/bin/oathtool -b --totp "${TOTP_SECRET}")"

echo -n "${PASSWORD_SHA256}${TOTP_AUTH_TOKEN}"
